export const servicesData = [
  {
    id: "ai-solutions",
    title: "Bespoke AI Solutions",
    description:
      "Custom ML models, AI integration, and data pipeline development tailored to your business needs.",
    icon: "🧠",
    gradient: "from-blue-500 to-purple-600",
    image_url:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    price_pkr_min: 50000,
    price_pkr_max: 200000,
    price_usd_min: 150,
    price_usd_max: 650,
    services_included: [
      "Custom ML Model Development",
      "AI System Integration",
      "Data Pipeline Architecture",
      "Predictive Analytics Implementation",
      "Computer Vision Solutions",
      "Natural Language Processing",
      "Model Deployment & Monitoring",
    ],
    tools: [
      "TensorFlow",
      "PyTorch",
      "AWS SageMaker",
      "Docker",
      "Kubernetes",
      "MLflow",
    ],
    deliverables: [
      "Trained and optimized ML models",
      "Complete system integration",
      "Documentation and training materials",
      "Deployment and monitoring setup",
      "Performance metrics and reporting",
    ],
    created_at: new Date(),
  },
  {
    id: "web-development",
    title: "Full-Stack Web Development",
    description:
      "Modern, scalable web applications built with cutting-edge technologies and best practices.",
    icon: "💻",
    gradient: "from-green-500 to-blue-600",
    image_url:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    price_pkr_min: 30000,
    price_pkr_max: 150000,
    price_usd_min: 100,
    price_usd_max: 500,
    services_included: [
      "Custom Web Application Development",
      "Responsive Design Implementation",
      "API Development & Integration",
      "Database Design & Optimization",
      "Cloud Deployment & Hosting",
      "Performance Optimization",
      "Maintenance & Support",
    ],
    tools: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Docker"],
    deliverables: [
      "Complete web application",
      "Responsive design across all devices",
      "Admin dashboard and analytics",
      "Documentation and source code",
      "Deployment and hosting setup",
    ],
    created_at: new Date(),
  },
  {
    id: "mobile-development",
    title: "Mobile App Development",
    description:
      "Native and cross-platform mobile applications for iOS and Android with modern UI/UX.",
    icon: "📱",
    gradient: "from-orange-500 to-red-600",
    image_url:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    price_pkr_min: 40000,
    price_pkr_max: 180000,
    price_usd_min: 130,
    price_usd_max: 600,
    services_included: [
      "Native iOS/Android Development",
      "Cross-platform Development",
      "UI/UX Design Implementation",
      "Backend API Integration",
      "App Store Deployment",
      "Push Notifications",
      "Analytics Integration",
    ],
    tools: [
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
      "Firebase",
      "App Store Connect",
    ],
    deliverables: [
      "Published mobile applications",
      "Source code and documentation",
      "App store optimization",
      "Analytics and crash reporting",
      "Post-launch support",
    ],
    created_at: new Date(),
  },
  {
    id: "data-analytics",
    title: "Data Analytics & Business Intelligence",
    description:
      "Transform your data into actionable insights with custom dashboards and analytics solutions.",
    icon: "📊",
    gradient: "from-purple-500 to-pink-600",
    image_url:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    price_pkr_min: 25000,
    price_pkr_max: 120000,
    price_usd_min: 80,
    price_usd_max: 400,
    services_included: [
      "Data Pipeline Development",
      "Custom Dashboard Creation",
      "Statistical Analysis",
      "Data Visualization",
      "Business Intelligence Reports",
      "Automated Reporting",
      "Data Quality Assessment",
    ],
    tools: [
      "Python",
      "Power BI",
      "Tableau",
      "SQL",
      "Apache Airflow",
      "Jupyter",
    ],
    deliverables: [
      "Interactive dashboards",
      "Automated reporting system",
      "Data pipeline documentation",
      "Training and knowledge transfer",
      "Ongoing support and maintenance",
    ],
    created_at: new Date(),
  },
  {
    id: "cloud-consulting",
    title: "Cloud Infrastructure & DevOps",
    description:
      "Scalable cloud solutions, infrastructure automation, and DevOps implementation.",
    icon: "☁️",
    gradient: "from-cyan-500 to-blue-600",
    image_url:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    price_pkr_min: 35000,
    price_pkr_max: 160000,
    price_usd_min: 115,
    price_usd_max: 525,
    services_included: [
      "Cloud Architecture Design",
      "Infrastructure as Code",
      "CI/CD Pipeline Setup",
      "Container Orchestration",
      "Security Implementation",
      "Cost Optimization",
      "24/7 Monitoring & Support",
    ],
    tools: [
      "AWS",
      "Terraform",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "Prometheus",
    ],
    deliverables: [
      "Complete cloud infrastructure",
      "Automated deployment pipelines",
      "Security and compliance setup",
      "Monitoring and alerting system",
      "Documentation and training",
    ],
    created_at: new Date(),
  },
  {
    id: "digital-transformation",
    title: "Digital Transformation Consulting",
    description:
      "End-to-end digital transformation strategy and implementation for modern businesses.",
    icon: "🚀",
    gradient: "from-indigo-500 to-purple-600",
    image_url:
      "https://images.unsplash.com/photo-1559136555-9303baea8ebd?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    price_pkr_min: 60000,
    price_pkr_max: 300000,
    price_usd_min: 200,
    price_usd_max: 1000,
    services_included: [
      "Digital Strategy Development",
      "Process Automation",
      "Legacy System Modernization",
      "Change Management",
      "Staff Training & Development",
      "Technology Integration",
      "Performance Measurement",
    ],
    tools: [
      "Custom Solutions",
      "Microsoft 365",
      "Salesforce",
      "SAP",
      "Various APIs",
    ],
    deliverables: [
      "Comprehensive digital strategy",
      "Modernized business processes",
      "Integrated technology stack",
      "Training programs",
      "Performance metrics dashboard",
    ],
    created_at: new Date(),
  },
];
